// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CryptoAppProject.Model;

[Table("log_activity")]
[Index("UserId", Name = "fk_log_activity_user_idx")]
public partial class LogActivity
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("User_Id")]
    public int UserId { get; set; }

    [Required]
    [StringLength(255)]
    public string Description { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("LogActivities")]
    public virtual User User { get; set; }
}